import { LyricSegmentIterator, LyricsScreen, compileLyricTimings, setScreenStartTimes, adjustScreenTimestamps, setSegmentEndTimes, createAssFile, createMultiVoiceAssFile, floatToTimecode, LyricsLine, KaraokeOptions, LyricEvent, VerticalAlignment, adjustSegmentTiming } from "./timing";
import { LYRIC_MARKERS } from "../constants";
import { LyricSegment } from "./timing";
import { COUNT_IN_SEGMENT_TEXT } from "./adjustments";

const DEFAULT_OPTIONS: KaraokeOptions = {
    addTitleScreen: true,
    addCountIns: true,
    addInstrumentalScreens: true,
    addStaggeredLines: true,
    useBackgroundVideo: false,
    verticalAlignment: VerticalAlignment.Middle,
    font: {
        size: 20,
        name: "Arial Narrow"
    },
    color: {
        background: { red: 255, green: 255, blue: 0 },
        primary: { red: 255, green: 0, blue: 255 },
        secondary: { red: 0, green: 255, blue: 255 }
    }
}

const DEFAULT_FONT_SIZE = 22;

export const testLyrics = "Be bop_a lu bop\nShe's my ba/by\n\nAnd_here's_screen_two"
const testEvents: LyricEvent[] = [
    [1.0, LYRIC_MARKERS.SEGMENT_START],
    [2.0, LYRIC_MARKERS.SEGMENT_END],
    [3.0, LYRIC_MARKERS.SEGMENT_START],
    [4.0, LYRIC_MARKERS.SEGMENT_START],
    [5.0, LYRIC_MARKERS.SEGMENT_START],
    [6.0, LYRIC_MARKERS.SEGMENT_START],
    [7.0, LYRIC_MARKERS.SEGMENT_START],
    [8.0, LYRIC_MARKERS.SEGMENT_START],
    [9.0, LYRIC_MARKERS.SEGMENT_START]
]

export const shortIntroTestEvents = testEvents;
const longIntroTestEvents: LyricEvent[] = [
    [6.0, LYRIC_MARKERS.SEGMENT_START],
    [7.0, LYRIC_MARKERS.SEGMENT_END],
    [8.0, LYRIC_MARKERS.SEGMENT_START],
    [9.0, LYRIC_MARKERS.SEGMENT_START],
    [10.0, LYRIC_MARKERS.SEGMENT_START],
    [11.0, LYRIC_MARKERS.SEGMENT_START],
    [12.0, LYRIC_MARKERS.SEGMENT_START],
    [13.0, LYRIC_MARKERS.SEGMENT_START],
    [14.0, LYRIC_MARKERS.SEGMENT_START]
]

const testAssPreamble = `[Script Info]
; Script generated by The Tüül - https://the-tuul.com
ScriptType: v4.00+
LayoutResX: 384
LayoutResY: 288
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial Narrow,20,&H00FF00FF,&H00FFFF00,&H0000FFFF,&H00000000,-1,0,0,0,100,100,0,0,1,1,0,8,0,0,0,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:04.00,Default,Singer,0,0,130,,{\\k0}{\\kf200}It's Cøøl to Tüül
Dialogue: 0,0:00:00.00,0:00:04.00,Default,Singer,0,0,160,,{\\k200}{\\kf200}TÜ/ÜL
`

const testAss = testAssPreamble + `Dialogue: 0,0:00:04.00,0:00:11.00,Default,Singer,0,0,130,,{\\k0}{\\kf200}${COUNT_IN_SEGMENT_TEXT}{\\kf100}Be bop {\\kf100}{\\kf100}a lu bop

Dialogue: 0,0:00:04.00,0:00:11.00,Default,Singer,0,0,160,,{\\k500}{\\kf100}She's my ba{\\kf100}by


Dialogue: 0,0:00:11.00,0:01:05.00,Default,Singer,0,0,145,,{\\k0}{\\kf100}And {\\kf100}here's {\\kf100}screen {\\kf5100}two
`

const longIntroTestAss = testAssPreamble + `Dialogue: 0,Default,0:00:04.00,0:00:15.00,130,{\\k300}{\\kf300}■■■■{\\kf100}Be bop {\\kf100}{\\kf100}a lu bop

Dialogue: 0,Default,0:00:04.00,0:00:15.00,130,{\\k900}{\\kf100}She's my ba{\\kf100}by


Dialogue: 0,0:00:11.00,0:01:05.00,Default,Singer,0,0,145,,{\\k0}{\\kf100}And {\\kf100}here's {\\kf100}screen {\\kf5100}two
`

describe('LyricSegmentIterator', () => {
    test('parses segments without markup', () => {
        const iterator = new LyricSegmentIterator(testLyrics);
        const segments = Array.from(iterator);
        expect(segments.length).toBe(8);
        expect(segments[0].text).toBe("Be bop ");
    });

    test('parses segments with markup', () => {
        const iterator = new LyricSegmentIterator(testLyrics, true);
        const segments = Array.from(iterator);
        expect(segments.length).toBe(8);
        expect(segments[0].text).toBe("Be bop_");
    });

    test('handles leading newlines', () => {
        const lyricsWithLeadingNewlines = "\n\nHello world";
        const iterator = new LyricSegmentIterator(lyricsWithLeadingNewlines);
        const segments = Array.from(iterator);
        expect(segments.length).toBe(1);
        expect(segments[0].text).toBe("Hello world");
    });

    test('handles only newlines', () => {
        const justNewlines = "\n\n\n";
        const iterator = new LyricSegmentIterator(justNewlines);
        const segments = Array.from(iterator);
        expect(segments.length).toBe(0);
    });

    test('trims leading spaces', () => {
        const lyrics = "Line 1\n Line 2";
        const iterator = new LyricSegmentIterator(lyrics);
        const segments = Array.from(iterator);
        expect(segments.length).toBe(2);
        expect(segments[1].text).toBe("Line 2");
    });
});

test('compileLyricTimings', () => {
    const screens = compileLyricTimings(testLyrics, testEvents);
    expect(screens.length).toBe(2);
    expect(screens[0].lines.length).toBe(2);
    expect(screens[0].lines[0].segments.length).toBe(2);
    expect(screens[1].lines[0].segments.length).toBe(4);
});

test('setSegmentEndTimes', () => {
    const initialScreens = compileLyricTimings(testLyrics, testEvents);
    const songDuration = 60;
    const screens = setSegmentEndTimes(initialScreens, songDuration);
    expect(screens[0].lines[0].segments[0].endTimestamp).toBe(2.0);
    expect(screens[0].lines[0].segments[1].endTimestamp).toBe(4.0);
    expect(screens[0].lines[1].segments[0].endTimestamp).toBe(5.0);
    expect(screens[0].lines[1].segments[1].endTimestamp).toBe(6.0);
    expect(screens[1].lines[0].segments[0].endTimestamp).toBe(7.0);

})

test('LyricSegment', () => {
    const segment = new LyricSegment("boop", 2.0, 3.0);
    expect(segment.toAss()).toBe("{\\kf100}boop")

    const underSecondSegment = new LyricSegment("baby", .5, .75);
    expect(underSecondSegment.toAss()).toBe("{\\kf25}baby");
});

// test('LyricScreen does ass', () => {
//     const screen = new LyricsScreen();
//     screen.toAss
// });

test('LyricScreen handles custom Y offset', () => {
    const screen = new LyricsScreen([
        new LyricsLine([new LyricSegment("one", 1.0)]),
        new LyricsLine([new LyricSegment("two", 2.0)])
    ])

    expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(127);

    screen.customFirstLineTopMargin = 50;
    expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(50);
    expect(screen.getLineY(1, DEFAULT_FONT_SIZE)).toBe(83);
})

test('LyricScreen respects vertical alignment', () => {
    const screen = new LyricsScreen([
        new LyricsLine([new LyricSegment("one", 1.0)]),
        new LyricsLine([new LyricSegment("two", 2.0)])
    ])

    expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(127);
    expect(screen.getLineY(0, DEFAULT_FONT_SIZE, VerticalAlignment.Top)).toBe(33);
    expect(screen.getLineY(0, DEFAULT_FONT_SIZE, VerticalAlignment.Bottom)).toBe(320 - (33 * 3));

    expect(screen.getLineY(1, DEFAULT_FONT_SIZE)).toBe(127 + 33);
    expect(screen.getLineY(1, DEFAULT_FONT_SIZE, VerticalAlignment.Top)).toBe(33 * 2);
    expect(screen.getLineY(1, DEFAULT_FONT_SIZE, VerticalAlignment.Bottom)).toBe(320 - (33 * 2));
});

test('setScreenStartTimes', () => {
    const screens = compileLyricTimings(testLyrics, testEvents);
    const adjusted = setScreenStartTimes(screens);
    expect(adjusted[0].startTimestamp).toBe(0.0);
});

test('adjustTimestamps', () => {
    const screens = setScreenStartTimes(compileLyricTimings(testLyrics, testEvents));

    const adjusted = adjustScreenTimestamps(screens, 1.0);
    expect(adjusted[0].lines[0].timestamp).toBe(2.0);
    expect(adjusted[0].startTimestamp).toBe(1.0)
});

test('createAssFileForShortIntroSong', () => {
    const songDuration = 60.0;
    const options: KaraokeOptions = { ...DEFAULT_OPTIONS, addInstrumentalScreens: false, addStaggeredLines: false }
    const assFile = createAssFile(testLyrics, shortIntroTestEvents, songDuration, "It's Cøøl to Tüül", "TÜ/ÜL", options);
    expect(assFile).toBe(testAss);
});

test('createAssFile handles timings without lyrics', () => {
    // A timings file can be loaded before lyrics are entered. That should
    // yield an event-less ASS file, not a crash in the screen decorators.
    const songDuration = 60.0;
    const timings: LyricEvent[] = [[1.0, LYRIC_MARKERS.SEGMENT_START], [2.0, LYRIC_MARKERS.SEGMENT_END]]
    const assFile = createAssFile("", timings, songDuration, "It's Cøøl to Tüül", "TÜ/ÜL", DEFAULT_OPTIONS);
    const headerOnly = testAssPreamble.slice(0, testAssPreamble.indexOf("Dialogue:"));
    expect(assFile).toBe(headerOnly);
});

test('addCountIn', () => {
    const songDuration = 60.0;
    const lyrics = "That was a long intro\nToo bad nothing rhymes with intro"
    const timings: LyricEvent[] = [[100.0, LYRIC_MARKERS.SEGMENT_START], [105.0, LYRIC_MARKERS.SEGMENT_START]]
    const options: KaraokeOptions = { ...DEFAULT_OPTIONS, addInstrumentalScreens: false, addStaggeredLines: false }
    let assFile = createAssFile(lyrics, timings, songDuration, "It's Cøøl to Tüül", "TÜ/ÜL", options);

    const expected = testAssPreamble + `Dialogue: 0,0:00:04.00,0:01:00.00,Default,Singer,0,0,130,,{\\k9400}{\\kf200}${COUNT_IN_SEGMENT_TEXT}{\\kf500}That was a long intro

Dialogue: 0,0:00:04.00,0:01:00.00,Default,Singer,0,0,160,,{\\k10100}{\\kf-4500}Too bad nothing rhymes with intro
`
    expect(assFile).toBe(expected);
});

test('addCountInToSevenSecondIntro', () => {
    // An intro between 7-8 seconds has a count-in that makes the intro between 4-5 seconds.
    // So we can't start playing audio until after the title screen.
    // So timings get moved up a little bit/
    const songDuration = 60.0;

    // a corner case when the first event is between 7 and 8 seconds
    const sevenSecondEvents: LyricEvent[] = [
        [7.5, LYRIC_MARKERS.SEGMENT_START],
        [8.5, LYRIC_MARKERS.SEGMENT_END],
        [9.0, LYRIC_MARKERS.SEGMENT_START],
        [10.0, LYRIC_MARKERS.SEGMENT_START],
        [11.0, LYRIC_MARKERS.SEGMENT_START],
        [12.0, LYRIC_MARKERS.SEGMENT_START],
        [13.0, LYRIC_MARKERS.SEGMENT_START],
        [14.0, LYRIC_MARKERS.SEGMENT_START],
        [15.0, LYRIC_MARKERS.SEGMENT_START],
    ]
    const sevenSecondAss = testAssPreamble + `Dialogue: 0,0:00:04.00,0:00:12.00,Default,Singer,0,0,130,,{\\k150}{\\kf200}${COUNT_IN_SEGMENT_TEXT}{\\kf100}Be bop {\\kf50}{\\kf100}a lu bop

Dialogue: 0,0:00:04.00,0:00:12.00,Default,Singer,0,0,160,,{\\k600}{\\kf100}She's my ba{\\kf100}by


Dialogue: 0,0:00:12.00,0:01:00.00,Default,Singer,0,0,145,,{\\k0}{\\kf100}And {\\kf100}here's {\\kf100}screen {\\kf4500}two
`
    const options: KaraokeOptions = { ...DEFAULT_OPTIONS, addInstrumentalScreens: false, addStaggeredLines: false }

    const assFile = createAssFile(testLyrics, sevenSecondEvents, songDuration, "It's Cøøl to Tüül", "TÜ/ÜL", options);
    expect(assFile).toBe(sevenSecondAss);

});

test('floatToTimecode', () => {
    expect(floatToTimecode(0)).toBe("0:00:00.00");
    expect(floatToTimecode(25.42)).toBe("0:00:25.42");
    expect(floatToTimecode(60)).toBe("0:01:00.00");
});

test('adjustSegmentTiming', () => {
    expect(adjustSegmentTiming(0, testEvents, { start: 0.5, end: 1.5 })[0][0]).toBe(0.5);
    expect(() => adjustSegmentTiming(8, testEvents, { start: 0.5, end: 1.5 })[0][0]).toThrow("Segment 8 not found in timings");
});

test('adjustSegmentTiming adds a SEGMENT_END to an open-ended segment', () => {
    // Segment 1 in testEvents has no SEGMENT_END (it runs straight into segment 2).
    const adjusted = adjustSegmentTiming(1, testEvents, { start: 3.0, end: 3.5 });
    // The new SEGMENT_END should appear between segment 1's SEGMENT_START (3.0)
    // and segment 2's SEGMENT_START (4.0).
    expect(adjusted[2]).toEqual([3.0, LYRIC_MARKERS.SEGMENT_START]);
    expect(adjusted[3]).toEqual([3.5, LYRIC_MARKERS.SEGMENT_END]);
    expect(adjusted[4]).toEqual([4.0, LYRIC_MARKERS.SEGMENT_START]);
});

test('adjustSegmentTiming removes an existing SEGMENT_END when end is undefined', () => {
    // Segment 0 in testEvents has an explicit SEGMENT_END at 2.0.
    const adjusted = adjustSegmentTiming(0, testEvents, { start: 1.0, end: undefined });
    // The SEGMENT_END marker should be gone; segment 1's SEGMENT_START at 3.0 follows directly.
    expect(adjusted[0]).toEqual([1.0, LYRIC_MARKERS.SEGMENT_START]);
    expect(adjusted[1]).toEqual([3.0, LYRIC_MARKERS.SEGMENT_START]);
    expect(adjusted.length).toBe(testEvents.length - 1);
});

test('adjustSegmentTiming adds a SEGMENT_END for the last segment in the array', () => {
    // Segment 7 (the last) has no SEGMENT_END and no following SEGMENT_START.
    const adjusted = adjustSegmentTiming(7, testEvents, { start: 9.0, end: 10.0 });
    expect(adjusted[adjusted.length - 2]).toEqual([9.0, LYRIC_MARKERS.SEGMENT_START]);
    expect(adjusted[adjusted.length - 1]).toEqual([10.0, LYRIC_MARKERS.SEGMENT_END]);
});

test('adjustSegmentTiming leaves an open-ended segment open when end stays undefined', () => {
    const adjusted = adjustSegmentTiming(2, testEvents, { start: 4.5, end: undefined });
    // Should be identical to testEvents except segment 2's start moved from 4.0 to 4.5.
    expect(adjusted.length).toBe(testEvents.length);
    expect(adjusted[3]).toEqual([4.5, LYRIC_MARKERS.SEGMENT_START]);
});

test('compileLyricTimings handles more events than segments', () => {
    // Test with only 1 segment but many events
    const shortLyrics = "Hello world";  // This creates 1 segment: "Hello world"
    const tooManyEvents: LyricEvent[] = [
        [1.0, LYRIC_MARKERS.SEGMENT_START],
        [2.0, LYRIC_MARKERS.SEGMENT_START], // This should trigger the error
        [3.0, LYRIC_MARKERS.SEGMENT_START],
        [4.0, LYRIC_MARKERS.SEGMENT_START],
        [5.0, LYRIC_MARKERS.SEGMENT_START]
    ];

    // Should return whatever screens were built before running out of segments
    const screens = compileLyricTimings(shortLyrics, tooManyEvents);
    expect(screens.length).toBe(1);
    expect(screens[0].lines.length).toBe(1);
    expect(screens[0].lines[0].segments.length).toBe(1); // Only got the first segment
});

describe("createMultiVoiceAssFile", () => {
    const noAuxOptions: KaraokeOptions = {
        ...DEFAULT_OPTIONS,
        addTitleScreen: false,
        addCountIns: false,
        addInstrumentalScreens: false,
        addStaggeredLines: false,
    };

    it("returns empty string when there are no tracks", () => {
        expect(createMultiVoiceAssFile([], 10, "T", "A")).toBe("");
    });

    it("emits one style per voice and events tagged with each voice's style", () => {
        const tracks = [
            { voice: "Anna", lyrics: "Hello\n", timings: [[1.0, LYRIC_MARKERS.SEGMENT_START]] as LyricEvent[], options: noAuxOptions },
            { voice: "Ben", lyrics: "World\n", timings: [[2.0, LYRIC_MARKERS.SEGMENT_START]] as LyricEvent[], options: noAuxOptions },
        ];
        const ass = createMultiVoiceAssFile(tracks, 10, "T", "A");

        // One style row per voice
        expect(ass).toContain("Style: V0,");
        expect(ass).toContain("Style: V1,");
        // Dialogue events reference each voice's style (",V0," is unique to events)
        expect(ass).toContain(",V0,");
        expect(ass).toContain(",V1,");
        // Both voices' lyrics are present
        expect(ass).toContain("Hello");
        expect(ass).toContain("World");
        // A single shared document (one [Events] section)
        expect(ass.match(/\[Events\]/g)?.length).toBe(1);
    });
});

describe("setSegmentEndTimes overlap clamp", () => {
    it("clamps an explicit end that extends past the next segment's start", () => {
        const s1 = new LyricSegment("a", 1.0, 5.0); // explicit end 5.0...
        const s2 = new LyricSegment("b", 3.0);      // ...but next segment starts at 3.0
        const screen = new LyricsScreen([new LyricsLine([s1, s2])]);
        setSegmentEndTimes([screen], 10);
        expect(s1.endTimestamp).toBe(3.0); // clamped to the next start
        expect(s2.endTimestamp).toBe(10);  // last segment inferred to song duration
    });

    it("leaves an explicit end that fits before the next segment", () => {
        const s1 = new LyricSegment("a", 1.0, 2.0);
        const s2 = new LyricSegment("b", 3.0);
        const screen = new LyricsScreen([new LyricsLine([s1, s2])]);
        setSegmentEndTimes([screen], 10);
        expect(s1.endTimestamp).toBe(2.0);
    });
});